version: 2.1

orbs:
  general: premiscale/general@1.0.8


executors:
  python3-10:
    docker:
      - image: cimg/python:3.10.6

  python3-9:
    docker:
      - image: cimg/python:3.9.12

  python3-8:
    docker:
      - image: cimg/python:3.8.13


workflows:
  src:
    jobs:
      - general/python-pylint:
          name: pylint
          modules_path: src/
          context: nexus

      - general/python-mypy:
          name: mypy [<< matrix.executor >>]
          configuration_file: pyproject.toml
          mypy-args: |
            --ignore-missing-imports
          matrix:
            parameters:
              executor:
                - python3-10
                - python3-9
                - python3-8
            alias: mypy

      # develop

      - general/python-release-poetry:
          name: twine upload [python-pypi]
          context: nexus
          repository: python-develop
          version: 0.0.<< pipeline.number >>
          pypirc-config: .pypirc
          requires:
            - pylint
            - mypy
          filters:
            branches:
              ignore:
                - master

      # master

      - general/python-release-poetry:
          name: twine upload [python-pypi]
          context: pypi
          repository: python-master
          version: 0.0.<< pipeline.number >>
          pypirc-config: .pypirc
          requires:
            - pylint
            - mypy
          filters:
            branches:
              only:
                - master